name: Perf

on:
  push:
    branches: [ main ]
  # enable users to manually trigger with workflow_dispatch
  workflow_dispatch:

jobs:
  test-perf-stat:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up perf (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-tools-common linux-tools-generic linux-tools-`uname -r`
          echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid
          perf stat echo 1
      - name: Run perf stat
        run: |
          perf stat --event cycles --log-fd 2 echo 1
      - name: Print exit status of last command
        run: |
          echo $?
  test-perf-record:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up perf (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-tools-common linux-tools-generic linux-tools-`uname -r`
          echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid
          perf stat echo 1
      - name: Run perf record
        run: |
          perf record --event cycles echo 1
      - name: Print exit status of last command
        run: |
          echo $?
      - name: Run perf report
        run: |
          perf report --stdio | grep cycles | wc -l
      - name: Run perf report -v
        run: |
          perf report -v --stdio | grep cycles | wc -l
      - name: Run perf report -q
        run: |
          perf report -q --stdio | grep cycles | wc -l
  test-perf-record-output:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up perf (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-tools-common linux-tools-generic linux-tools-`uname -r`
          echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid
          perf stat echo 1
      - name: Run perf record
        run: |
          perf record --event cycles --output perf-record-validate.data echo 1
      - name: Print exit status of last command
        run: |
          echo $?
      - name: Run perf report
        run: |
          perf report -i perf-record-validate.data --stdio
      - name: Run perf report and check presence of event
        run: |
          perf report -i perf-record-validate.data --stdio | grep cycles | wc -l
  test-perf-record-output-multi:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up perf (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-tools-common linux-tools-generic linux-tools-`uname -r`
          echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid
          perf stat echo 1
      - name: Run perf list
        run: |
          perf list
      - name: Run perf record
        run: |
          perf record --event cycles,cpu-clock --output perf-record-validate.data echo 1
      - name: Print exit status of last command
        run: |
          echo $?
      - name: Run perf report
        run: |
          perf report -i perf-record-validate.data --stdio
      - name: Run perf report and check presence of events
        run: |
          perf report -i perf-record-validate.data --stdio | grep -E 'cycles|cpu-clock' | wc -l
  test-perf-stats:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up perf (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-tools-common linux-tools-generic linux-tools-`uname -r`
          echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid
          perf stat echo 1
      - name: Run perf list
        run: |
          perf list
      - name: Run perf record then perf report stats
        run: |
          perf record --event cycles -o - true | perf report -i - --stats
      - name: Print exit status of last command
        run: |
          echo $?
      - name: Run perf record then perf report stats and check presence of event
        run: |
          perf record --event cycles -o - true | perf report -i - --stats | grep cycles | wc -l
  test-perf-stats-multi:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up perf (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-tools-common linux-tools-generic linux-tools-`uname -r`
          echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid
          perf stat echo 1
      - name: Run perf list
        run: |
          perf list
      - name: Run perf record then perf report stats
        run: |
          perf record --event cycles,cpu-clock -o - true | perf report -i - --stats
      - name: Print exit status of last command
        run: |
          echo $?
      - name: Run perf record then perf report stats and check presence of event
        run: |
          perf record --event cycles -o - true | perf report -i - --stats | grep -E 'cycles|cpu-clock' | wc -l
